subscribers:
  camera_reading:
    topic: /usb_cam/image_raw
    queue_size: 1
  obstacle_reading:
    topic: /tracked_obstacles
    queue_size: 100
  velocity_reading:
    topic: /vel_msg
    queue_size: 100

publishers:
  control_data:
    topic: /ctl_msg
    queue_size: 1
  lane_coef:
    topic: /lane_msg
    queue_size: 10

LaneDetector:  
  steer_angle: 0.0
  eL_height: 0.2
  e1_height: 1.2563
  trust_height: 0.6667
  lp: 609.3 

ROI:
  dynamic_roi: true
  threshold: 170
  
image_view:
  enable_opencv: false
  wait_key_delay: 1
  enable_console_output: false
