subscribers:

  camera_reading:
    topic: /usb_cam/image_raw
    queue_size: 1

publishers:

  control_data:
    topic: /twist_msg
    queue_size: 1

params:

  speed_limits:
    max: 1.0
    min: -1.0

  angle_limits:
    max: 1.0
    min: -1.0

LaneDetector:
  
  sob_min_th: 175
  sob_max_th: 255
  his_min_th: 175
  hls_max_th: 255
  
  pid_params:
    Kp: 1.0
    Ki: 0.00001
    Kd: 0.0025
    dt: 0.1



image_view:

  enable_opencv: true
  wait_key_delay: 1
  enable_console_output: true
