subscribers:
  camera_reading:
    topic: /usb_cam/image_raw
    queue_size: 1
  obstacle_reading:
    topic: /raw_obstacles
    queue_size: 100
  velocity_reading:
    topic: /vel_msg
    queue_size: 100

publishers:
  control_data:
    topic: /twist_msg
    queue_size: 1
  lane_coef:
    topic: /lane_msg
    queue_size: 10

params:
  truck_info: LV
  udp_group_addr: 239.255.255.250
  udp_group_port: 9307 
  target_vel: 1.00
  safety_vel: 0.45
  fv_max_vel: 1.20
  lv_stop_dist: 0.5
  fv_stop_dist: 0.3
  safety_dist: 1.5
  target_dist: 0.8
  angle_degree: 0.0
  Kp_d: 1.2
  Ki_d: 0.2
  
ROI:
  width: 640
  height: 480
  top_gap: 0.406
  bot_gap: 0.185
  top_height: 0.99
  bot_height: 0.47
  extra: 0.00
  extra_up: 140
  extra_down: 180
  distance: 200

LaneDetector:  
  sob_min_th: 175
  sob_max_th: 255
  his_min_th: 175
  hls_max_th: 255
  pid_params:
    Kp: 0.5
    Ki: 0.001
    Kd: 0.01
    dt: 0.1
  filter_param: 10
  steer_angle: 0.0
  eL_height: 0.2
  e1_height: 1.4694
  trust_height: 0.6667
  lp: 607.3 
  <!-- K1: 0.15 -->
  <!-- K2: 0.15 -->

image_view:
  enable_opencv: true
  wait_key_delay: 1
  enable_console_output: true

