subscribers:
  camera_reading:
    topic: /usb_cam/image_raw
    queue_size: 10
  obstacle_reading:
    topic: /raw_obstacles
    queue_size: 100

publishers:
  control_data:
    topic: /twist_msg
    queue_size: 1

params:
  center_err: 640
  target_speed: 0.6
  target_Dist: 0.3
  angle_degree: 0.0
  speed_limits:
    max: 5.0
    min: 0.0
  angle_limits:
    max: 60.0
    min: -60.0

ROI:
  width: 1280
  height: 720
  top_gap: 0.326
  bot_gap: 0.098
  top_height: 0.903
  bot_height: 0.528
  extra: 0.00
  extra_up: -75
  extra_down: 100

LaneDetector:  
  sob_min_th: 175
  sob_max_th: 255
  his_min_th: 175
  hls_max_th: 255
  pid_params:
    Kp: 0.7
    Ki: 0.0001
    Kd: 0.0025
    dt: 0.1

image_view:
  enable_opencv: true
  wait_key_delay: 1
  enable_console_output: true

