subscribers:
  camera_reading:
    topic: /usb_cam/image_raw
    queue_size: 10
  obstacle_reading:
    topic: /raw_obstacles
    queue_size: 100

publishers:
  control_data:
    topic: /twist_msg
    queue_size: 1

params:
  center_err: 640
  speed_mode: 5
  target_speed: 0.65
  safety_speed: 0.45
  target_dist: 0.5
  safety_dist: 1.5
  angle_degree: 0.0
  speed_limits:
    max: 5.0
    min: 0.0
  angle_limits:
    max: 60.0
    min: -60.0
  pid:
    Kp: 8.0
    Ki: 0.0001
    Kd: 0.75
  width2dist: 30
  dist: 55
 
ROI:
  width: 1280
  height: 720
  top_gap: 0.306
  bot_gap: 0.048
  top_height: 0.903
  bot_height: 0.508
  extra: 0.00
  extra_up: 0
  extra_down: 0

LaneDetector:  
  sob_min_th: 175
  sob_max_th: 255
  his_min_th: 175
  hls_max_th: 255
  pid_params:
    Kp: 0.5
    Ki: 0.001
    Kd: 0.01
    dt: 0.1
  filter_param: 10
  center_height: 0.4

image_view:
  enable_opencv: false
  wait_key_delay: 1
  enable_console_output: true

