subscribers:
  camera_reading:
    topic: /usb_cam/image_raw
    queue_size: 10
  obstacle_reading:
    topic: /raw_obstacles
    queue_size: 100

publishers:
  control_data:
    topic: /twist_msg
    queue_size: 1

params:
  truck_info: LV
  udp_group_addr: 239.255.255.250
  udp_group_port: 9307 
  center_err: 640
  target_vel: 0.80
  safety_vel: 0.45
  target_dist: 0.5
  safety_dist: 1.5
  angle_degree: 0.0
  
ROI:
  width: 1280
  height: 720
  top_gap: 0.306
  bot_gap: 0.048
  top_height: 0.903
  bot_height: 0.508
  extra: 0.00
  extra_up: 0
  extra_down: 0

LaneDetector:  
  sob_min_th: 175
  sob_max_th: 255
  his_min_th: 175
  hls_max_th: 255
  pid_params:
    Kp: 0.5
    Ki: 0.001
    Kd: 0.01
    dt: 0.1
  filter_param: 10
  eL_height: 0.2
  e1_height: 1.4375
  trust_height: 0.6667
  lp: 891 
  K1: 0.04
  K2: 0.04
  steer_angle: 0.0

image_view:
  enable_opencv: true
  wait_key_delay: 1
  enable_console_output: true

